# -*- coding: utf-8 -*-
"""RRHH.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1ti91TjDIHAL8Eeu-yyoSypZgNGS4VHME
"""

#Conexión con colab
from google.colab import drive
drive.mount('/content/drive')

#Importar paquetes
import pandas as pd
import numpy as np

"""LEER BASES DE DATOS"""

#BASE DE DATOS 1: employee_survey_data.csv
#Encuesta realizada a los empleados sobre satisfacción laboral
# ID empleado / Satisfacción del Medio Amb / Satisfacción Laboral / Equilibrio trabajo-vida
satisf = pd.read_csv('/content/drive/MyDrive/CursoAnalitica3/employee_survey_data.csv', sep = ';')
satisf.head(2)

#BASE DE DATOS 2: general_data.csv 
#Información general de los empleados
info = pd.read_csv('/content/drive/MyDrive/CursoAnalitica3/general_data.csv', sep = ';')
info.head(2)

#BASE DE DATOS 3: in_time.csv
#Registro de la hora de ingreso de los empleados
entrada = pd.read_csv('/content/drive/MyDrive/CursoAnalitica3/in_time.csv', sep = ';')
entrada.head(2)

#BASE DE DATOS 4: manager_survey_data.csv
#Encuesta de desempeño de los empleados realizada por parte de los jefes.
encues = pd.read_csv('/content/drive/MyDrive/CursoAnalitica3/manager_survey_data.csv', sep = ';')
encues.head(2)

#BASE DE DATOS 5: out_time.csv
#Registro de la hora de salida de los empleados
salida = pd.read_csv('/content/drive/MyDrive/CursoAnalitica3/out_time.csv', sep = ';')
salida.head(2)

#BASE DE DATOS 6: retirement_info.csv
#Información de retiro de los empleados que dejaron la empresa.
retiro = pd.read_csv('/content/drive/MyDrive/CursoAnalitica3/retirement_info.csv', sep = ';')
retiro.head(2)

"""DEPURACIÓN BASES DE DATOS

-base 2 (información general)
"""

info.head(10)

#Inciamos con la depuración de la base de datos 2, que tiene información general de los empleados
info.columns

#conocer el tipo de variables
info.dtypes

#imprimir categorias de las variables
lista = ['BusinessTravel', 'Department', 'EducationField', 'Gender', 'JobRole', 'MaritalStatus', 'Over18']
for i in lista:
    print(info[i].value_counts())
    print('------------------------------------')

#definimos un nuevo DF con las variables de interés
info2 = info[['EmployeeID', 'Gender', 'Age', 'Department', 'Education',
       'EducationField', 'JobLevel',
       'JobRole', 'MaritalStatus', 'MonthlyIncome', 'NumCompaniesWorked', 'PercentSalaryHike', 'StandardHours', 'StockOptionLevel',
       'TotalWorkingYears', 'TrainingTimesLastYear', 'YearsAtCompany',
       'YearsSinceLastPromotion', 'YearsWithCurrManager']]
info2.head()

#tratamiento de datos nulos
info2.isnull().sum()

#reemplazar daros nulos por '0'
info2 = info2.fillna(0)
info2.isnull().sum()

"""-base 1 (encuesta satisfaccion a los empleados)"""

satisf.head(8)
#ID empleado / Satisfacción : ambiente / laboral / equilibrio vida - trabajo

#imprimir categorias de las variables
lista = ['EnvironmentSatisfaction', 'JobSatisfaction', 'WorkLifeBalance']
for i in lista:
    print(satisf[i].value_counts())
    print('------------------------------------')

#tratamiento de datos nulos
satisf.isnull().sum()

#reemplazar daros nulos por '0'
satisf = satisf.fillna(0)
satisf.isnull().sum()

"""-base 4 (encuesta de desempeño de los empleados hecha por los jefes)"""

encues.head(8)
#nivel de participación en el trabajo / calificación de desempeño del año anterior

#imprimir categorias de las variables
lista = ['JobInvolvement', 'PerformanceRating']
for i in lista:
    print(encues[i].value_counts())
    print('------------------------------------')

#tratamiento de datos nulos
encues.isnull().sum()

"""-base 6 (información de retiro)"""

retiro.head(8)
# desgaste / fecha de retiro / tipo de retiro / motivo de renuncia

#imprimir categorias de las variables
lista = ['Attrition', 'retirementType', 'resignationReason']
for i in lista:
    print(retiro[i].value_counts())
    print('------------------------------------')

#tratamiento de datos nulos
retiro.isnull().sum()

#reemplazar daros nulos por '0'
retiro = retiro.fillna('sin inf')
retiro.isnull().sum()
